In [1]:
import os
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import warnings

from src.results_utils import create_results_df, RESULTS_DIR
from src.plots_utils import (
    create_results_bar_plot,
    save_plot,
    create_results_point_plot,
)

TABLES_DIR = os.path.abspath(os.path.join(".", "tables"))
os.makedirs(TABLES_DIR, exist_ok=True)


def save_to_csv(df, filename):
    """Save DataFrame to CSV."""
    filepath = os.path.join(TABLES_DIR, filename)
    df.to_csv(filepath, index=False)


warnings.filterwarnings("ignore")

# Datasets Info

In [2]:
dataset_info = pd.read_csv(os.path.join(RESULTS_DIR, "data_comphrasion_df.csv"))
dataset_info.head(10)

,dataset,ratio (0 : 1),shape,inbalance strength,class negative num,class positive num,is_large,is_additional
0,Breast Cancer Wisconsin (Diagnostic),357:212,"(569, 30)",1.68,357,212,False,True
1,Ionosphere,14:25,"(351, 34)",1.79,126,225,False,True
2,Pima Indians Diabetes,125:67,"(768, 8)",1.87,500,268,False,True
3,ecoli,43:5,"(336, 7)",8.60,301,35,False,False
4,optical_digits,2533:277,"(5620, 64)",9.14,5066,554,False,False
5,satimage,5809:626,"(6435, 36)",9.28,5809,626,False,False
6,pen_digits,9937:1055,"(10992, 16)",9.42,9937,1055,False,False
7,abalone,3786:391,"(4177, 10)",9.68,3786,391,False,False
8,sick_euthyroid,2870:293,"(3163, 42)",9.80,2870,293,False,False
9,spectrometer,54:5,"(531, 93)",10.80,486,45,False,False

# Experiments Results

In [4]:
results_df = pd.read_json(
    os.path.join(
        RESULTS_DIR, "run_inspire_ignore_additional_datasets_small/results.json"
    ),
    lines=True
)

In [6]:
results_df

,params,elapsed,estimated_operations,train,test
0,"{'n_estimators': 100, 'oversampling_neighbors'...",0.152051,5.151332e+06,"{'accuracy': 0.9402985075, 'f1': 0.68, 'recall...","{'accuracy': 0.8823529412000001, 'f1': 0.60000..."
1,"{'n_estimators': 100, 'oversampling_neighbors'...",0.158138,4.355214e+06,"{'accuracy': 0.9440298507, 'f1': 0.7058823529,...","{'accuracy': 0.8823529412000001, 'f1': 0.60000..."
2,"{'n_estimators': 100, 'oversampling_neighbors'...",0.235596,6.371094e+06,"{'accuracy': 0.9365671642000001, 'f1': 0.65306...","{'accuracy': 0.8823529412000001, 'f1': 0.60000..."
3,"{'n_estimators': 100, 'oversampling_neighbors'...",0.186987,7.928657e+06,"{'accuracy': 0.9440298507, 'f1': 0.7058823529,...","{'accuracy': 0.8823529412000001, 'f1': 0.60000..."
4,"{'n_estimators': 100, 'oversampling_neighbors'...",0.232464,6.504946e+06,"{'accuracy': 0.9402985075, 'f1': 0.68, 'recall...","{'accuracy': 0.8823529412000001, 'f1': 0.60000..."
...,...,...,...,...,...
5755,"{'n_estimators': 500, 'oversampling_neighbors'...",2.146072,9.006437e+07,"{'accuracy': 1.0, 'f1': 1.0, 'recall': 1.0, 'p...","{'accuracy': 0.9826589595, 'f1': 0.88888888890..."
5756,"{'n_estimators': 500, 'oversampling_neighbors'...",2.385251,8.780024e+07,"{'accuracy': 1.0, 'f1': 1.0, 'recall': 1.0, 'p...","{'accuracy': 0.9826589595, 'f1': 0.88888888890..."
5757,"{'n_estimators': 500, 'oversampling_neighbors'...",3.975136,1.096738e+08,"{'accuracy': 1.0, 'f1': 1.0, 'recall': 1.0, 'p...","{'accuracy': 0.9884393064, 'f1': 0.92857142860..."
5758,"{'n_estimators': 500, 'oversampling_neighbors'...",2.250788,7.639586e+07,"{'accuracy': 1.0, 'f1': 1.0, 'recall': 1.0, 'p...","{'accuracy': 0.9826589595, 'f1': 0.88888888890..."
5759,"{'n_estimators': 500, 'oversampling_neighbors'...",3.997525,1.695984e+08,"{'accuracy': 1.0, 'f1': 1.0, 'recall': 1.0, 'p...","{'accuracy': 0.9826589595, 'f1': 0.88888888890..."

In [7]:
results_df.reset_index(inplace=True)

In [12]:
datasets = dataset_info[(dataset_info["is_large"] == False) & (dataset_info["is_additional"] == False)]["dataset"].to_numpy()

In [13]:
datasets

array(['ecoli', 'optical_digits', 'satimage', 'pen_digits', 'abalone',
       'sick_euthyroid', 'spectrometer', 'car_eval_34', 'us_crime',
       'yeast_ml8', 'scene', 'libras_move', 'thyroid_sick', 'coil_2000',
       'arrhythmia', 'solar_flare_m0', 'oil', 'car_eval_4',
       'wine_quality', 'letter_img', 'yeast_me2', 'ozone_level',
       'mammography', 'abalone_19'], dtype=object)

In [ ]:
results_df["dataset_name"] = results_df["index"].apply(lambda x: datasets[x // 144])

,index,params,elapsed,estimated_operations,train,test
0,0,"{'n_estimators': 100, 'oversampling_neighbors'...",0.152051,5.151332e+06,"{'accuracy': 0.9402985075, 'f1': 0.68, 'recall...","{'accuracy': 0.8823529412000001, 'f1': 0.60000..."
1,1,"{'n_estimators': 100, 'oversampling_neighbors'...",0.158138,4.355214e+06,"{'accuracy': 0.9440298507, 'f1': 0.7058823529,...","{'accuracy': 0.8823529412000001, 'f1': 0.60000..."
2,2,"{'n_estimators': 100, 'oversampling_neighbors'...",0.235596,6.371094e+06,"{'accuracy': 0.9365671642000001, 'f1': 0.65306...","{'accuracy': 0.8823529412000001, 'f1': 0.60000..."
3,3,"{'n_estimators': 100, 'oversampling_neighbors'...",0.186987,7.928657e+06,"{'accuracy': 0.9440298507, 'f1': 0.7058823529,...","{'accuracy': 0.8823529412000001, 'f1': 0.60000..."
4,4,"{'n_estimators': 100, 'oversampling_neighbors'...",0.232464,6.504946e+06,"{'accuracy': 0.9402985075, 'f1': 0.68, 'recall...","{'accuracy': 0.8823529412000001, 'f1': 0.60000..."
...,...,...,...,...,...,...
5755,5755,"{'n_estimators': 500, 'oversampling_neighbors'...",2.146072,9.006437e+07,"{'accuracy': 1.0, 'f1': 1.0, 'recall': 1.0, 'p...","{'accuracy': 0.9826589595, 'f1': 0.88888888890..."
5756,5756,"{'n_estimators': 500, 'oversampling_neighbors'...",2.385251,8.780024e+07,"{'accuracy': 1.0, 'f1': 1.0, 'recall': 1.0, 'p...","{'accuracy': 0.9826589595, 'f1': 0.88888888890..."
5757,5757,"{'n_estimators': 500, 'oversampling_neighbors'...",3.975136,1.096738e+08,"{'accuracy': 1.0, 'f1': 1.0, 'recall': 1.0, 'p...","{'accuracy': 0.9884393064, 'f1': 0.92857142860..."
5758,5758,"{'n_estimators': 500, 'oversampling_neighbors'...",2.250788,7.639586e+07,"{'accuracy': 1.0, 'f1': 1.0, 'recall': 1.0, 'p...","{'accuracy': 0.9826589595, 'f1': 0.88888888890..."
5759,5759,"{'n_estimators': 500, 'oversampling_neighbors'...",3.997525,1.695984e+08,"{'accuracy': 1.0, 'f1': 1.0, 'recall': 1.0, 'p...","{'accuracy': 0.9826589595, 'f1': 0.88888888890..."

In [5]:
results_df = results_df.merge(
    dataset_info, left_on="dataset_name", right_on="dataset", how="left"
)

KeyError: 'dataset_name'

## Preparation

In [6]:
results_df["param_name"] = results_df["params"].apply(
    lambda row: ", ".join(
        f"{k}={v}" for k, v in sorted(row.items(), key=lambda x: x[0])
    )
)
results_df["oversampling_hue"] = (
    results_df["oversampler_name"] + "_" + results_df["n_neighbors"].astype(str)
)

results_df.sort_values(
    ["oversampling_option", "n_neighbors", "oversampler_name"],
    inplace=True,
    ascending=False,
)
results_df.reset_index(drop=True, inplace=True)

In [7]:
datasets = results_df.dataset_name.unique()
datasets

array(['ecoli', 'optical_digits', 'satimage', 'pen_digits', 'abalone',
       'sick_euthyroid', 'spectrometer', 'car_eval_34', 'us_crime',
       'yeast_ml8', 'scene', 'libras_move', 'thyroid_sick', 'coil_2000',
       'arrhythmia', 'solar_flare_m0', 'oil', 'car_eval_4',
       'wine_quality', 'letter_img', 'yeast_me2', 'ozone_level',
       'mammography', 'abalone_19',
       'Breast Cancer Wisconsin (Diagnostic)', 'Ionosphere',
       'Pima Indians Diabetes'], dtype=object)

In [8]:
results_df.head(10)

,params,elapsed,estimated_operations,dataset_name,oversampler_name,model_name,n_neighbors,take,oversampling_option,accuracy,...,dataset,ratio (0 : 1),shape,inbalance strength,class negative num,class positive num,is_large,is_additional,param_name,oversampling_hue
0,"{'criterion': 'gini', 'max_depth': 5, 'max_fea...",0.102145,3.092292e+06,ecoli,SMOTE,DecisionTree,7,1,BASIC,0.852941,...,ecoli,43:5,"(336, 7)",8.6,301,35,False,False,"criterion=gini, max_depth=5, max_features=None...",SMOTE_7
1,"{'criterion': 'gini', 'max_depth': 5, 'max_fea...",0.111311,4.256938e+06,ecoli,SMOTE,DecisionTree,7,1,BASIC,0.852941,...,ecoli,43:5,"(336, 7)",8.6,301,35,False,False,"criterion=gini, max_depth=5, max_features=None...",SMOTE_7
2,"{'criterion': 'gini', 'max_depth': 5, 'max_fea...",0.108658,3.280344e+06,ecoli,SMOTE,DecisionTree,7,1,BASIC,0.852941,...,ecoli,43:5,"(336, 7)",8.6,301,35,False,False,"criterion=gini, max_depth=5, max_features=None...",SMOTE_7
3,"{'criterion': 'gini', 'max_depth': 5, 'max_fea...",0.110634,5.773941e+06,ecoli,SMOTE,DecisionTree,7,1,BASIC,0.852941,...,ecoli,43:5,"(336, 7)",8.6,301,35,False,False,"criterion=gini, max_depth=5, max_features=None...",SMOTE_7
4,"{'criterion': 'gini', 'max_depth': 5, 'max_fea...",0.112613,3.395251e+06,ecoli,SMOTE,DecisionTree,7,1,BASIC,0.852941,...,ecoli,43:5,"(336, 7)",8.6,301,35,False,False,"criterion=gini, max_depth=5, max_features=None...",SMOTE_7
5,"{'criterion': 'gini', 'max_depth': 5, 'max_fea...",0.150090,4.352657e+06,ecoli,SMOTE,DecisionTree,7,1,BASIC,0.852941,...,ecoli,43:5,"(336, 7)",8.6,301,35,False,False,"criterion=gini, max_depth=5, max_features=None...",SMOTE_7
6,"{'criterion': 'gini', 'max_depth': 5, 'max_fea...",0.106825,4.085358e+06,ecoli,SMOTE,DecisionTree,7,1,BASIC,0.852941,...,ecoli,43:5,"(336, 7)",8.6,301,35,False,False,"criterion=gini, max_depth=5, max_features=None...",SMOTE_7
7,"{'criterion': 'gini', 'max_depth': 5, 'max_fea...",0.115303,6.017599e+06,ecoli,SMOTE,DecisionTree,7,1,BASIC,0.852941,...,ecoli,43:5,"(336, 7)",8.6,301,35,False,False,"criterion=gini, max_depth=5, max_features=None...",SMOTE_7
8,"{'criterion': 'gini', 'max_depth': 5, 'max_fea...",0.110572,3.206628e+06,ecoli,SMOTE,DecisionTree,7,1,BASIC,0.852941,...,ecoli,43:5,"(336, 7)",8.6,301,35,False,False,"criterion=gini, max_depth=5, max_features=None...",SMOTE_7
9,"{'criterion': 'gini', 'max_depth': 5, 'max_fea...",0.091998,4.801325e+06,ecoli,SMOTE,DecisionTree,7,1,BASIC,0.911765,...,ecoli,43:5,"(336, 7)",8.6,301,35,False,False,"criterion=gini, max_depth=5, max_features=sqrt...",SMOTE_7

In [9]:
agg_results_df = (
    results_df.groupby(
        [
            "dataset_name",
            "param_name",
            "oversampler_name",
            "n_neighbors",
            "oversampling_option",
        ]
    )["f1"]
    .agg(["mean", "std"])
    .reset_index()
)

In [10]:
unique_methods = np.sort(agg_results_df["oversampler_name"].unique())
unique_neighbors = np.sort(agg_results_df["n_neighbors"].unique())

base_colors = sns.color_palette("husl", n_colors=len(unique_methods))
base_colors = {name: color for name, color in zip(unique_methods, base_colors)}

pallette = {}
for k in unique_neighbors:
    for name, color in base_colors.items():
        if k == 3:
            color = tuple(c * 1.25 for c in color)
        elif k == 7:
            color = tuple(c * 0.75 for c in color)
        pallette[f"{name}_{k}"] = np.clip(color, 0.0, 1.0)

In [11]:
agg_results_df_ultimate = (
    results_df.groupby(
        ["dataset_name", "oversampler_name", "n_neighbors", "oversampling_option"]
    )["f1"]
    .agg(["mean", "std"])
    .reset_index()
)

In [11]:
save_to_csv(agg_results_df_ultimate, "results_agg_ultimate.csv")
save_to_csv(agg_results_df, "results_agg.csv")

# Analysis

In [12]:
comparison_info_detailed = agg_results_df.pivot(
    columns=["n_neighbors", "oversampling_option"],
    index=["dataset_name", "param_name", "oversampler_name"],
    values=["mean", "std"],
)
save_to_csv(comparison_info_detailed, "comparison_info_detailed.csv")
comparison_info_detailed.sort_index().head(10)

                                                                                                              mean  \
n_neighbors                                                                                                      3
oversampling_option                                                                                       ADVANCED
dataset_name                         param_name                                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) criterion=entropy, max_depth=10, max_features=N... ADASYN            0.950000
                                                                                        BorderlineSMOTE   0.950000
                                                                                        SMOTE             0.965366
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.950000
                                                                                        BorderlineSMOTE   0.950000
                                                                                        SMOTE             0.975610
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.950000
                                                                                        BorderlineSMOTE   0.960244
                                                                                        SMOTE             0.975610
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.950000

                                                                                                                    \
n_neighbors
oversampling_option                                                                                          BASIC
dataset_name                         param_name                                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) criterion=entropy, max_depth=10, max_features=N... ADASYN            0.945366
                                                                                        BorderlineSMOTE   0.975610
                                                                                        SMOTE             0.970488
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.950000
                                                                                        BorderlineSMOTE   0.975610
                                                                                        SMOTE             0.970488
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.945366
                                                                                        BorderlineSMOTE   0.975610
                                                                                        SMOTE             0.970488
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.950000

                                                                                                                    \
n_neighbors                                                                                                      5
oversampling_option                                                                                       ADVANCED
dataset_name                         param_name                                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) criterion=entropy, max_depth=10, max_features=N... ADASYN            0.955122
                                                                                        BorderlineSMOTE   0.960244
                                                                                        SMOTE             0.965366
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.950000
                                                                                        BorderlineSMOTE   0.955122
                                                                                        SMOTE             0.975610
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.955122
                                                                                        BorderlineSMOTE   0.955122
                                                                                        SMOTE             0.970488
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.950000

                                                                                                                    \
n_neighbors
oversampling_option                                                                                          BASIC
dataset_name                         param_name                                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) criterion=entropy, max_depth=10, max_features=N... ADASYN            0.940732
                                                                                        BorderlineSMOTE   0.960244
                                                                                        SMOTE             0.955122
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.945366
                                                                                        BorderlineSMOTE   0.950000
                                                                                        SMOTE             0.950000
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.940732
                                                                                        BorderlineSMOTE   0.955122
                                                                                        SMOTE             0.955122
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.945366

                                                                                                                    \
n_neighbors                                                                                                      7
oversampling_option                                                                                       ADVANCED
dataset_name                         param_name                                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) criterion=entropy, max_depth=10, max_features=N... ADASYN            0.965366
                                                                                        BorderlineSMOTE   0.965366
                                                                                        SMOTE             0.970488
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.965366
                                                                                        BorderlineSMOTE   0.965366
                                                                                        SMOTE             0.975610
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.960244
                                                                                        BorderlineSMOTE   0.960244
                                                                                        SMOTE             0.970488
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.960244

                                                                                                                    \
n_neighbors
oversampling_option                                                                                          BASIC
dataset_name                         param_name                                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) criterion=entropy, max_depth=10, max_features=N... ADASYN            0.965366
                                                                                        BorderlineSMOTE   0.965366
                                                                                        SMOTE             0.965366
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.965366
                                                                                        BorderlineSMOTE   0.950000
                                                                                        SMOTE             0.975610
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.965366
                                                                                        BorderlineSMOTE   0.960244
                                                                                        SMOTE             0.965366
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.975610

                                                                                                               std  \
n_neighbors                                                                                                      3
oversampling_option                                                                                       ADVANCED
dataset_name                         param_name                                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) criterion=entropy, max_depth=10, max_features=N... ADASYN            0.000000
                                                                                        BorderlineSMOTE   0.000000
                                                                                        SMOTE             0.014027
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.000000
                                                                                        BorderlineSMOTE   0.000000
                                                                                        SMOTE             0.000000
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.000000
                                                                                        BorderlineSMOTE   0.014027
                                                                                        SMOTE             0.000000
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.000000

                                                                                                                    \
n_neighbors
oversampling_option                                                                                          BASIC
dataset_name                         param_name                                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) criterion=entropy, max_depth=10, max_features=N... ADASYN            0.010362
                                                                                        BorderlineSMOTE   0.000000
                                                                                        SMOTE             0.011453
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.000000
                                                                                        BorderlineSMOTE   0.000000
                                                                                        SMOTE             0.011453
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.010362
                                                                                        BorderlineSMOTE   0.000000
                                                                                        SMOTE             0.011453
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.000000

                                                                                                                    \
n_neighbors                                                                                                      5
oversampling_option                                                                                       ADVANCED
dataset_name                         param_name                                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) criterion=entropy, max_depth=10, max_features=N... ADASYN            0.011453
                                                                                        BorderlineSMOTE   0.014027
                                                                                        SMOTE             0.014027
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.000000
                                                                                        BorderlineSMOTE   0.011453
                                                                                        SMOTE             0.000000
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.011453
                                                                                        BorderlineSMOTE   0.011453
                                                                                        SMOTE             0.011453
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.000000

                                                                                                                    \
n_neighbors
oversampling_option                                                                                          BASIC
dataset_name                         param_name                                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) criterion=entropy, max_depth=10, max_features=N... ADASYN            0.012691
                                                                                        BorderlineSMOTE   0.014027
                                                                                        SMOTE             0.011453
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.010362
                                                                                        BorderlineSMOTE   0.000000
                                                                                        SMOTE             0.000000
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.012691
                                                                                        BorderlineSMOTE   0.011453
                                                                                        SMOTE             0.011453
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.010362

                                                                                                                    \
n_neighbors                                                                                                      7
oversampling_option                                                                                       ADVANCED
dataset_name                         param_name                                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) criterion=entropy, max_depth=10, max_features=N... ADASYN            0.014027
                                                                                        BorderlineSMOTE   0.014027
                                                                                        SMOTE             0.011453
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.014027
                                                                                        BorderlineSMOTE   0.014027
                                                                                        SMOTE             0.000000
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.014027
                                                                                        BorderlineSMOTE   0.014027
                                                                                        SMOTE             0.011453
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.014027


n_neighbors
oversampling_option                                                                                          BASIC
dataset_name                         param_name                                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) criterion=entropy, max_depth=10, max_features=N... ADASYN            0.014027
                                                                                        BorderlineSMOTE   0.014027
                                                                                        SMOTE             0.014027
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.014027
                                                                                        BorderlineSMOTE   0.000000
                                                                                        SMOTE             0.000000
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.014027
                                                                                        BorderlineSMOTE   0.014027
                                                                                        SMOTE             0.014027
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.000000

In [13]:
def select_option(group):
    # If the two mean values are equal, return a row with oversampling_option set to "EQUAL"
    if group["mean"].nunique() == 1:
        return pd.Series(
            {
                "dataset_name": group["dataset_name"].iloc[0],
                "oversampler_name": group["oversampler_name"].iloc[0],
                "n_neighbors": group["n_neighbors"].iloc[0],
                "oversampling_option": "EQUAL",
            }
        )
    else:
        # Otherwise, select the row with the maximum mean value
        idx = group["mean"].idxmax()
        return group.loc[
            idx,
            ["dataset_name", "oversampler_name", "n_neighbors", "oversampling_option"],
        ]

In [14]:
comparison_info_detailed_exploded = comparison_info_detailed.stack(
    level=[1, 2]
).reset_index()

max_options_detailed = (
    comparison_info_detailed_exploded.groupby(
        ["dataset_name", "oversampler_name", "n_neighbors", "param_name"]
    )
    .apply(select_option)
    .reset_index(drop=True)
)
max_options_detailed = max_options_detailed.reset_index(drop=True)

max_options_detailed

,dataset_name,oversampler_name,n_neighbors,oversampling_option
0,Breast Cancer Wisconsin (Diagnostic),ADASYN,3,ADVANCED
1,Breast Cancer Wisconsin (Diagnostic),ADASYN,3,EQUAL
2,Breast Cancer Wisconsin (Diagnostic),ADASYN,3,ADVANCED
3,Breast Cancer Wisconsin (Diagnostic),ADASYN,3,EQUAL
4,Breast Cancer Wisconsin (Diagnostic),ADASYN,3,EQUAL
...,...,...,...,...
52483,yeast_ml8,SMOTE,7,BASIC
52484,yeast_ml8,SMOTE,7,BASIC
52485,yeast_ml8,SMOTE,7,BASIC
52486,yeast_ml8,SMOTE,7,BASIC
52487,yeast_ml8,SMOTE,7,BASIC

In [15]:
aggregated_stats_df_detailed = pd.DataFrame(
    max_options_detailed.groupby(["oversampler_name", "n_neighbors"])[
        "oversampling_option"
    ].value_counts()
)
aggregated_stats_df_detailed

                                                  count
oversampler_name n_neighbors oversampling_option
ADASYN           3           ADVANCED              3102
                             BASIC                 2114
                             EQUAL                  616
                 5           ADVANCED              3508
                             BASIC                 1835
                             EQUAL                  489
                 7           EQUAL                 2661
                             ADVANCED              2226
                             BASIC                  945
BorderlineSMOTE  3           ADVANCED              3159
                             BASIC                 2063
                             EQUAL                  610
                 5           ADVANCED              3479
                             BASIC                 1866
                             EQUAL                  487
                 7           ADVANCED              2774
                             EQUAL                 1681
                             BASIC                 1377
SMOTE            3           ADVANCED              3422
                             BASIC                 1812
                             EQUAL                  598
                 5           ADVANCED              3261
                             BASIC                 2034
                             EQUAL                  537
                 7           ADVANCED              3299
                             BASIC                 1957
                             EQUAL                  576

In [16]:
comparison_info_ultimate = agg_results_df_ultimate.pivot(
    columns=["n_neighbors", "oversampling_option"],
    index=["dataset_name", "oversampler_name"],
    values=["mean", "std"],
)
save_to_csv(comparison_info_ultimate, "comparison_info_ultimate.csv")
comparison_info_ultimate.sort_index().head(10)

                                                           mean            \
n_neighbors                                                   3
oversampling_option                                    ADVANCED     BASIC
dataset_name                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) ADASYN            0.946658  0.940817
                                     BorderlineSMOTE   0.957486  0.952214
                                     SMOTE             0.950486  0.949457
Ionosphere                           ADASYN            0.978396  0.982152
                                     BorderlineSMOTE   0.972696  0.958757
                                     SMOTE             0.974008  0.970847
Pima Indians Diabetes                ADASYN            0.673334  0.686724
                                     BorderlineSMOTE   0.660920  0.652248
                                     SMOTE             0.640247  0.609827
abalone                              ADASYN            0.420222  0.421155

                                                                           \
n_neighbors                                                   5
oversampling_option                                    ADVANCED     BASIC
dataset_name                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) ADASYN            0.950050  0.936599
                                     BorderlineSMOTE   0.958829  0.947766
                                     SMOTE             0.951916  0.948221
Ionosphere                           ADASYN            0.977692  0.969302
                                     BorderlineSMOTE   0.977151  0.974257
                                     SMOTE             0.977882  0.978800
Pima Indians Diabetes                ADASYN            0.664919  0.664142
                                     BorderlineSMOTE   0.667808  0.654560
                                     SMOTE             0.644659  0.683684
abalone                              ADASYN            0.418404  0.408118

                                                                           \
n_neighbors                                                   7
oversampling_option                                    ADVANCED     BASIC
dataset_name                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) ADASYN            0.954246  0.946413
                                     BorderlineSMOTE   0.960391  0.939292
                                     SMOTE             0.953088  0.949394
Ionosphere                           ADASYN            0.980241  0.969163
                                     BorderlineSMOTE   0.977805  0.969551
                                     SMOTE             0.978301  0.969849
Pima Indians Diabetes                ADASYN            0.670838  0.655055
                                     BorderlineSMOTE   0.668068  0.640103
                                     SMOTE             0.644991  0.673241
abalone                              ADASYN            0.416444       NaN

                                                            std            \
n_neighbors                                                   3
oversampling_option                                    ADVANCED     BASIC
dataset_name                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) ADASYN            0.020996  0.028567
                                     BorderlineSMOTE   0.015927  0.029392
                                     SMOTE             0.027836  0.028313
Ionosphere                           ADASYN            0.012403  0.016004
                                     BorderlineSMOTE   0.013647  0.017020
                                     SMOTE             0.012514  0.013410
Pima Indians Diabetes                ADASYN            0.026491  0.023176
                                     BorderlineSMOTE   0.033860  0.027812
                                     SMOTE             0.034729  0.023155
abalone                              ADASYN            0.036410  0.036031

                                                                           \
n_neighbors                                                   5
oversampling_option                                    ADVANCED     BASIC
dataset_name                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) ADASYN            0.020715  0.029653
                                     BorderlineSMOTE   0.016322  0.023965
                                     SMOTE             0.026760  0.022900
Ionosphere                           ADASYN            0.011141  0.013802
                                     BorderlineSMOTE   0.011942  0.014525
                                     SMOTE             0.009818  0.016967
Pima Indians Diabetes                ADASYN            0.027594  0.030663
                                     BorderlineSMOTE   0.030367  0.023002
                                     SMOTE             0.033887  0.032240
abalone                              ADASYN            0.036912  0.030307


n_neighbors                                                   7
oversampling_option                                    ADVANCED     BASIC
dataset_name                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) ADASYN            0.021341  0.028464
                                     BorderlineSMOTE   0.016588  0.030531
                                     SMOTE             0.025619  0.029505
Ionosphere                           ADASYN            0.012416  0.021484
                                     BorderlineSMOTE   0.013406  0.014333
                                     SMOTE             0.008204  0.014517
Pima Indians Diabetes                ADASYN            0.026970  0.021439
                                     BorderlineSMOTE   0.030125  0.028534
                                     SMOTE             0.032838  0.029425
abalone                              ADASYN            0.036409       NaN

In [17]:
max_options_ultimate = (
    max_options_detailed.groupby(["dataset_name", "oversampler_name", "n_neighbors"])[
        "oversampling_option"
    ]
    .agg(
        lambda x: "EQUAL"
        if x.value_counts().get("ADVANCED", 0) == x.value_counts().get("BASIC", 0)
        else x.value_counts().idxmax()
    )
    .reset_index()
)

max_options_ultimate = max_options_ultimate.reset_index(drop=True)

max_options_ultimate

,dataset_name,oversampler_name,n_neighbors,oversampling_option
0,Breast Cancer Wisconsin (Diagnostic),ADASYN,3,ADVANCED
1,Breast Cancer Wisconsin (Diagnostic),ADASYN,5,ADVANCED
2,Breast Cancer Wisconsin (Diagnostic),ADASYN,7,ADVANCED
3,Breast Cancer Wisconsin (Diagnostic),BorderlineSMOTE,3,BASIC
4,Breast Cancer Wisconsin (Diagnostic),BorderlineSMOTE,5,ADVANCED
...,...,...,...,...
238,yeast_ml8,BorderlineSMOTE,5,BASIC
239,yeast_ml8,BorderlineSMOTE,7,BASIC
240,yeast_ml8,SMOTE,3,BASIC
241,yeast_ml8,SMOTE,5,BASIC
242,yeast_ml8,SMOTE,7,BASIC

In [18]:
aggregated_stats_df_ultimate = pd.DataFrame(
    max_options_ultimate.groupby(["oversampler_name", "n_neighbors"])[
        "oversampling_option"
    ].value_counts()
)
aggregated_stats_df_ultimate

                                                  count
oversampler_name n_neighbors oversampling_option
ADASYN           3           ADVANCED                14
                             BASIC                   10
                             EQUAL                    3
                 5           ADVANCED                19
                             BASIC                    6
                             EQUAL                    2
                 7           ADVANCED                12
                             EQUAL                   12
                             BASIC                    3
BorderlineSMOTE  3           ADVANCED                17
                             BASIC                    8
                             EQUAL                    2
                 5           ADVANCED                20
                             BASIC                    5
                             EQUAL                    2
                 7           ADVANCED                14
                             EQUAL                    8
                             BASIC                    5
SMOTE            3           ADVANCED                20
                             BASIC                    5
                             EQUAL                    2
                 5           ADVANCED                17
                             BASIC                    7
                             EQUAL                    3
                 7           ADVANCED                19
                             BASIC                    6
                             EQUAL                    2

# Charts

## Basic comparison top 3

In [21]:
for dataset in datasets:
    df = results_df[results_df["dataset_name"] == dataset]
    df_agg = agg_results_df[agg_results_df["dataset_name"] == dataset]

    best_params = (
        df_agg.sort_values("mean", ascending=False)["param_name"].head(3).to_numpy()
    )
    ratio = dataset_info[dataset_info["dataset"] == dataset]["ratio (0 : 1)"].values[0]

    figure, axs = plt.subplots(
        nrows=3, ncols=1, figsize=(20, 12), sharey=True, sharex=True
    )
    axs = axs.flatten()

    for i, (ax, param) in enumerate(zip(axs, best_params)):
        cur_df = df[df["param_name"] == param]
        create_results_bar_plot(ax=ax, df=cur_df, param=param, pallette=pallette, i=i)

    plt.suptitle(f"F1 Score Comparison for {dataset} (Ratio: {ratio})", fontsize=20)
    plt.tight_layout()
    save_plot(
        os.path.join("basic_comparison_top_3", f"f1_score_comparison_{dataset}.png")
    )

## Basic comparison middle 3

In [21]:
for dataset in datasets:
    df = results_df[results_df["dataset_name"] == dataset]
    df_agg = agg_results_df[agg_results_df["dataset_name"] == dataset]
    df_agg_sorted = df_agg.sort_values("mean", ascending=False)

    # Calculate the indices for the middle three.
    num_params = len(df_agg_sorted)
    if num_params < 3:
        middle_indices = list(range(num_params))
    else:
        start_index = (num_params - 3) // 2
        middle_indices = list(range(start_index, start_index + 3))

    best_params = df_agg_sorted.iloc[middle_indices]["param_name"].to_numpy()

    ratio = dataset_info[dataset_info["dataset"] == dataset]["ratio (0 : 1)"].values[0]

    figure, axs = plt.subplots(
        nrows=3, ncols=1, figsize=(20, 12), sharey=True, sharex=True
    )
    axs = axs.flatten()

    for i, (ax, param) in enumerate(zip(axs, best_params)):
        cur_df = df[df["param_name"] == param]
        create_results_bar_plot(ax=ax, df=cur_df, param=param, pallette=pallette, i=i)

    plt.suptitle(f"F1 Score Comparison for {dataset} (Ratio: {ratio})\nMiddle 3 Performing Parameters", fontsize=20)
    plt.tight_layout()
    save_plot(
        os.path.join("basic_comparison_middle_3", f"f1_score_comparison_{dataset}.png")
    )

## Other charts

In [ ]:
aggregated_stats_df_detailed = aggregated_stats_df_detailed.reset_index()
aggregated_stats_df_detailed["oversampling_hue"] = (
    aggregated_stats_df_detailed["oversampler_name"]
    + "_"
    + aggregated_stats_df_detailed["n_neighbors"].astype(str)
)

fig, ax = plt.subplots(figsize=(12, 6))

create_results_bar_plot(
    ax=ax,
    df=aggregated_stats_df_detailed,
    param="oversampling_option",
    pallette=pallette,
    target="count",
    y_label="Count",
    bbox_right=1.22,
    round_digits=0,
)

save_plot(os.path.join("comparison", "detailed_scores.png"))

In [ ]:
aggregated_stats_df_ultimate = aggregated_stats_df_ultimate.reset_index()
aggregated_stats_df_ultimate["oversampling_hue"] = (
    aggregated_stats_df_ultimate["oversampler_name"]
    + "_"
    + aggregated_stats_df_ultimate["n_neighbors"].astype(str)
)

fig, ax = plt.subplots(figsize=(12, 6))

create_results_bar_plot(
    ax=ax,
    df=aggregated_stats_df_ultimate,
    param="oversampling_option",
    pallette=pallette,
    target="count",
    y_label="Count",
    bbox_right=1.22,
    round_digits=0,
)

save_plot(os.path.join("comparison", "ultimate_scores.png"))

In [ ]:
fig, axs = plt.subplots(
    nrows=len(unique_methods),
    ncols=len(unique_neighbors),
    figsize=(7 * len(unique_neighbors), 4 * len(unique_methods)),
    sharex=True,
    sharey=True,
)

unique_neighbors = sorted(results_df["n_neighbors"].unique())
for i, method in enumerate(unique_methods):
    for j, n_val in enumerate(unique_neighbors):
        ax = (
            axs[i, j]
            if (len(unique_methods) > 1 and len(unique_neighbors) > 1)
            else axs[max(i, j)]
        )
        subset = results_df[
            (results_df["oversampler_name"] == method)
            & (results_df["n_neighbors"] == n_val)
        ]

        # Use the pre-defined palette for the current method and n_neighbors
        palette_key = f"{method}_{n_val}"
        current_palette = {
            opt: pallette.get(palette_key)
            for opt in subset["oversampling_option"].unique()
        }
        plot_legend = i == 0 and j == len(unique_neighbors) - 1

        create_results_point_plot(
            df=subset,
            method=method,
            n_val=n_val,
            ax=ax,
            pallette=current_palette,
            plot_legend=plot_legend,
            target_y="f1",
            scale=0.8,
            capsize=0.1,
        )

plt.suptitle(
    "Mean F1 Score Comparison by Inbalance Strength and Oversampling Method",
    fontsize=20,
    y=1.00,
)
plt.tight_layout()

save_plot(os.path.join("comparison", "mean_f1_over_imbalance_strength.png"))

In [19]:
results_df["dataset_size"] = (
    results_df["class negative num"] + results_df["class positive num"]
).astype(int)


fig, axs = plt.subplots(
    nrows=len(unique_methods),
    ncols=len(unique_neighbors),
    figsize=(7 * len(unique_neighbors), 4 * len(unique_methods)),
    sharex=True,
    sharey=True,
)

unique_neighbors = sorted(results_df["n_neighbors"].unique())
for i, method in enumerate(unique_methods):
    for j, n_val in enumerate(unique_neighbors):
        ax = (
            axs[i, j]
            if (len(unique_methods) > 1 and len(unique_neighbors) > 1)
            else axs[max(i, j)]
        )
        subset = results_df[
            (results_df["oversampler_name"] == method)
            & (results_df["n_neighbors"] == n_val)
        ]

        # Use the pre-defined palette for the current method and n_neighbors
        palette_key = f"{method}_{n_val}"
        current_palette = {
            opt: pallette.get(palette_key)
            for opt in subset["oversampling_option"].unique()
        }
        plot_legend = i == 0 and j == len(unique_neighbors) - 1

        create_results_point_plot(
            df=subset,
            method=method,
            n_val=n_val,
            ax=ax,
            pallette=current_palette,
            plot_legend=plot_legend,
            target_x="dataset_size",
            target_y="f1",
            x_label="Dataset Size",
            scale=0.8,
            capsize=0.1,
            x_discrete=False

        )
plt.suptitle(
    "Mean F1 Score Comparison by Dataset Size and Oversampling Method",
    fontsize=20,
    y=1.00,
)
plt.tight_layout()

save_plot(os.path.join("comparison", "mean_f1_over_dataset_size.png"))

# Missing results

In [ ]:
from bagging_smote import PARAM_GRID
from sklearn.model_selection import ParameterGrid

param_grid_size = len(list(ParameterGrid(PARAM_GRID)))
print("PARAM_GRID length (exploded):", param_grid_size)

PARAM_GRID length (exploded): 216

In [ ]:
missing_df = results_df.groupby(
    ["dataset_name", "oversampling_option", "oversampler_name", "n_neighbors", "take"]
)["params"].count()
missing_df.to_csv(os.path.join(TABLES_DIR, "results_params_count.csv"))

In [ ]:
missing_df = pd.DataFrame(missing_df[missing_df < param_grid_size])
missing_df["missing"] = param_grid_size - missing_df["params"]
missing_df

,,,,,params,missing
dataset_name,oversampling_option,oversampler_name,n_neighbors,take,,
car_eval_4,BASIC,BorderlineSMOTE,7,1,200,16