In [1]:
import os
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import warnings

from src.results_utils import create_results_df, RESULTS_DIR
from src.plots_utils import create_results_bar_plot, save_plot

TABLES_DIR = os.path.abspath(os.path.join(".", "tables"))
os.makedirs(TABLES_DIR, exist_ok=True)


def save_to_csv(df, filename):
    """Save DataFrame to CSV."""
    filepath = os.path.join(TABLES_DIR, filename)
    df.to_csv(filepath, index=False)


warnings.filterwarnings("ignore")

# Datasets Info

In [2]:
dataset_info = pd.read_csv(os.path.join(RESULTS_DIR, "data_comphrasion_df.csv"))
dataset_info.head(10)

,dataset,ratio (0 : 1),shape,inbalance strength,class negative num,class positive num,is_large,is_additional
0,Breast Cancer Wisconsin (Diagnostic),357:212,"(569, 30)",1.68,357,212,False,True
1,Ionosphere,14:25,"(351, 34)",1.79,126,225,False,True
2,Pima Indians Diabetes,125:67,"(768, 8)",1.87,500,268,False,True
3,ecoli,43:5,"(336, 7)",8.60,301,35,False,False
4,optical_digits,2533:277,"(5620, 64)",9.14,5066,554,False,False
5,satimage,5809:626,"(6435, 36)",9.28,5809,626,False,False
6,pen_digits,9937:1055,"(10992, 16)",9.42,9937,1055,False,False
7,abalone,3786:391,"(4177, 10)",9.68,3786,391,False,False
8,sick_euthyroid,2870:293,"(3163, 42)",9.80,2870,293,False,False
9,spectrometer,54:5,"(531, 93)",10.80,486,45,False,False

# Experiments Results

In [3]:
results_df = create_results_df()

print("Number of rows in results_df:", results_df.shape[0])

Number of rows in results_df: 459848

## Preparation

In [4]:
results_df["param_name"] = results_df["params"].apply(
    lambda row: ", ".join(
        f"{k}={v}" for k, v in sorted(row.items(), key=lambda x: x[0])
    )
)
results_df["oversampling_hue"] = (
    results_df["oversampler_name"] + "_" + results_df["n_neighbors"].astype(str)
)

results_df.sort_values(
    ["oversampling_option", "n_neighbors", "oversampler_name"],
    inplace=True,
    ascending=False,
)
results_df.reset_index(drop=True, inplace=True)

In [5]:
datasets = results_df.dataset_name.unique()
datasets

array(['ecoli', 'optical_digits', 'satimage', 'pen_digits', 'abalone',
       'sick_euthyroid', 'spectrometer', 'car_eval_34', 'us_crime',
       'yeast_ml8', 'scene', 'libras_move', 'thyroid_sick', 'coil_2000',
       'arrhythmia', 'solar_flare_m0', 'oil', 'car_eval_4',
       'wine_quality', 'letter_img', 'yeast_me2', 'ozone_level',
       'mammography', 'abalone_19',
       'Breast Cancer Wisconsin (Diagnostic)', 'Ionosphere',
       'Pima Indians Diabetes'], dtype=object)

In [6]:
results_df.head(10)

,params,elapsed,estimated_operations,dataset_name,oversampler_name,model_name,n_neighbors,take,oversampling_option,accuracy,f1,recall,precision,roc_auc,param_name,oversampling_hue
0,"{'criterion': 'gini', 'max_depth': 5, 'max_fea...",0.102145,3.092292e+06,ecoli,SMOTE,DecisionTree,7,1,BASIC,0.852941,0.545455,0.75,0.428571,0.945833,"criterion=gini, max_depth=5, max_features=None...",SMOTE_7
1,"{'criterion': 'gini', 'max_depth': 5, 'max_fea...",0.111311,4.256938e+06,ecoli,SMOTE,DecisionTree,7,1,BASIC,0.852941,0.545455,0.75,0.428571,0.945833,"criterion=gini, max_depth=5, max_features=None...",SMOTE_7
2,"{'criterion': 'gini', 'max_depth': 5, 'max_fea...",0.108658,3.280344e+06,ecoli,SMOTE,DecisionTree,7,1,BASIC,0.852941,0.545455,0.75,0.428571,0.954167,"criterion=gini, max_depth=5, max_features=None...",SMOTE_7
3,"{'criterion': 'gini', 'max_depth': 5, 'max_fea...",0.110634,5.773941e+06,ecoli,SMOTE,DecisionTree,7,1,BASIC,0.852941,0.545455,0.75,0.428571,0.945833,"criterion=gini, max_depth=5, max_features=None...",SMOTE_7
4,"{'criterion': 'gini', 'max_depth': 5, 'max_fea...",0.112613,3.395251e+06,ecoli,SMOTE,DecisionTree,7,1,BASIC,0.852941,0.545455,0.75,0.428571,0.954167,"criterion=gini, max_depth=5, max_features=None...",SMOTE_7
5,"{'criterion': 'gini', 'max_depth': 5, 'max_fea...",0.150090,4.352657e+06,ecoli,SMOTE,DecisionTree,7,1,BASIC,0.852941,0.545455,0.75,0.428571,0.954167,"criterion=gini, max_depth=5, max_features=None...",SMOTE_7
6,"{'criterion': 'gini', 'max_depth': 5, 'max_fea...",0.106825,4.085358e+06,ecoli,SMOTE,DecisionTree,7,1,BASIC,0.852941,0.545455,0.75,0.428571,0.945833,"criterion=gini, max_depth=5, max_features=None...",SMOTE_7
7,"{'criterion': 'gini', 'max_depth': 5, 'max_fea...",0.115303,6.017599e+06,ecoli,SMOTE,DecisionTree,7,1,BASIC,0.852941,0.545455,0.75,0.428571,0.945833,"criterion=gini, max_depth=5, max_features=None...",SMOTE_7
8,"{'criterion': 'gini', 'max_depth': 5, 'max_fea...",0.110572,3.206628e+06,ecoli,SMOTE,DecisionTree,7,1,BASIC,0.852941,0.545455,0.75,0.428571,0.945833,"criterion=gini, max_depth=5, max_features=None...",SMOTE_7
9,"{'criterion': 'gini', 'max_depth': 5, 'max_fea...",0.091998,4.801325e+06,ecoli,SMOTE,DecisionTree,7,1,BASIC,0.911765,0.727273,1.00,0.571429,0.970833,"criterion=gini, max_depth=5, max_features=sqrt...",SMOTE_7

In [7]:
agg_results_df = (
    results_df.groupby(
        [
            "dataset_name",
            "param_name",
            "oversampler_name",
            "n_neighbors",
            "oversampling_option",
        ]
    )["f1"]
    .agg(["mean", "std"])
    .reset_index()
)

In [8]:
unique_methods = np.sort(agg_results_df["oversampler_name"].unique())
unique_neighbors = np.sort(agg_results_df["n_neighbors"].unique())

base_colors = sns.color_palette("husl", n_colors=len(unique_methods))
base_colors = {name: color for name, color in zip(unique_methods, base_colors)}

pallette = {}
for k in unique_neighbors:
    for name, color in base_colors.items():
        if k == 3:
            color = tuple(c * 1.25 for c in color)
        elif k == 7:
            color = tuple(c * 0.75 for c in color)
        pallette[f"{name}_{k}"] = np.clip(color, 0.0, 1.0)

In [9]:
agg_results_df_ultimate = (
    results_df.groupby(
        ["dataset_name", "oversampler_name", "n_neighbors", "oversampling_option"]
    )["f1"]
    .agg(["mean", "std"])
    .reset_index()
)

In [10]:
save_to_csv(agg_results_df_ultimate, "results_agg_ultimate.csv")
save_to_csv(agg_results_df, "results_agg.csv")

# Analysis

In [11]:
comparison_info_detailed = agg_results_df.pivot(
    columns=["n_neighbors", "oversampling_option"],
    index=["dataset_name", "param_name", "oversampler_name"],
    values=["mean", "std"],
)
save_to_csv(comparison_info_detailed, "comparison_info_detailed.csv")
comparison_info_detailed.sort_index().head(10)

                                                                                                              mean  \
n_neighbors                                                                                                      3
oversampling_option                                                                                       ADVANCED
dataset_name                         param_name                                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) criterion=entropy, max_depth=10, max_features=N... ADASYN            0.950000
                                                                                        BorderlineSMOTE   0.950000
                                                                                        SMOTE             0.965366
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.950000
                                                                                        BorderlineSMOTE   0.950000
                                                                                        SMOTE             0.975610
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.950000
                                                                                        BorderlineSMOTE   0.960244
                                                                                        SMOTE             0.975610
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.950000

                                                                                                                    \
n_neighbors
oversampling_option                                                                                          BASIC
dataset_name                         param_name                                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) criterion=entropy, max_depth=10, max_features=N... ADASYN                 NaN
                                                                                        BorderlineSMOTE        NaN
                                                                                        SMOTE             0.975610
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN                 NaN
                                                                                        BorderlineSMOTE        NaN
                                                                                        SMOTE             0.962805
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN                 NaN
                                                                                        BorderlineSMOTE        NaN
                                                                                        SMOTE             0.962805
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN                 NaN

                                                                                                                    \
n_neighbors                                                                                                      5
oversampling_option                                                                                       ADVANCED
dataset_name                         param_name                                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) criterion=entropy, max_depth=10, max_features=N... ADASYN                 NaN
                                                                                        BorderlineSMOTE        NaN
                                                                                        SMOTE             0.965366
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN                 NaN
                                                                                        BorderlineSMOTE        NaN
                                                                                        SMOTE             0.975610
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN                 NaN
                                                                                        BorderlineSMOTE        NaN
                                                                                        SMOTE             0.970488
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN                 NaN

                                                                                                                \
n_neighbors
oversampling_option                                                                                      BASIC
dataset_name                         param_name                                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) criterion=entropy, max_depth=10, max_features=N... ADASYN             NaN
                                                                                        BorderlineSMOTE    NaN
                                                                                        SMOTE              NaN
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN             NaN
                                                                                        BorderlineSMOTE    NaN
                                                                                        SMOTE              NaN
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN             NaN
                                                                                        BorderlineSMOTE    NaN
                                                                                        SMOTE              NaN
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN             NaN

                                                                                                                   \
n_neighbors                                                                                                     7
oversampling_option                                                                                      ADVANCED
dataset_name                         param_name                                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) criterion=entropy, max_depth=10, max_features=N... ADASYN                NaN
                                                                                        BorderlineSMOTE       NaN
                                                                                        SMOTE                 NaN
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN                NaN
                                                                                        BorderlineSMOTE       NaN
                                                                                        SMOTE                 NaN
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN                NaN
                                                                                        BorderlineSMOTE       NaN
                                                                                        SMOTE                 NaN
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN                NaN

                                                                                                                \
n_neighbors
oversampling_option                                                                                      BASIC
dataset_name                         param_name                                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) criterion=entropy, max_depth=10, max_features=N... ADASYN             NaN
                                                                                        BorderlineSMOTE    NaN
                                                                                        SMOTE              NaN
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN             NaN
                                                                                        BorderlineSMOTE    NaN
                                                                                        SMOTE              NaN
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN             NaN
                                                                                        BorderlineSMOTE    NaN
                                                                                        SMOTE              NaN
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN             NaN

                                                                                                               std  \
n_neighbors                                                                                                      3
oversampling_option                                                                                       ADVANCED
dataset_name                         param_name                                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) criterion=entropy, max_depth=10, max_features=N... ADASYN            0.000000
                                                                                        BorderlineSMOTE   0.000000
                                                                                        SMOTE             0.014027
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.000000
                                                                                        BorderlineSMOTE   0.000000
                                                                                        SMOTE             0.000000
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.000000
                                                                                        BorderlineSMOTE   0.014027
                                                                                        SMOTE             0.000000
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN            0.000000

                                                                                                                    \
n_neighbors
oversampling_option                                                                                          BASIC
dataset_name                         param_name                                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) criterion=entropy, max_depth=10, max_features=N... ADASYN                 NaN
                                                                                        BorderlineSMOTE        NaN
                                                                                        SMOTE             0.000000
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN                 NaN
                                                                                        BorderlineSMOTE        NaN
                                                                                        SMOTE             0.018109
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN                 NaN
                                                                                        BorderlineSMOTE        NaN
                                                                                        SMOTE             0.018109
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN                 NaN

                                                                                                                    \
n_neighbors                                                                                                      5
oversampling_option                                                                                       ADVANCED
dataset_name                         param_name                                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) criterion=entropy, max_depth=10, max_features=N... ADASYN                 NaN
                                                                                        BorderlineSMOTE        NaN
                                                                                        SMOTE             0.014027
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN                 NaN
                                                                                        BorderlineSMOTE        NaN
                                                                                        SMOTE             0.000000
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN                 NaN
                                                                                        BorderlineSMOTE        NaN
                                                                                        SMOTE             0.011453
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN                 NaN

                                                                                                                \
n_neighbors
oversampling_option                                                                                      BASIC
dataset_name                         param_name                                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) criterion=entropy, max_depth=10, max_features=N... ADASYN             NaN
                                                                                        BorderlineSMOTE    NaN
                                                                                        SMOTE              NaN
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN             NaN
                                                                                        BorderlineSMOTE    NaN
                                                                                        SMOTE              NaN
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN             NaN
                                                                                        BorderlineSMOTE    NaN
                                                                                        SMOTE              NaN
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN             NaN

                                                                                                                   \
n_neighbors                                                                                                     7
oversampling_option                                                                                      ADVANCED
dataset_name                         param_name                                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) criterion=entropy, max_depth=10, max_features=N... ADASYN                NaN
                                                                                        BorderlineSMOTE       NaN
                                                                                        SMOTE                 NaN
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN                NaN
                                                                                        BorderlineSMOTE       NaN
                                                                                        SMOTE                 NaN
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN                NaN
                                                                                        BorderlineSMOTE       NaN
                                                                                        SMOTE                 NaN
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN                NaN


n_neighbors
oversampling_option                                                                                      BASIC
dataset_name                         param_name                                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) criterion=entropy, max_depth=10, max_features=N... ADASYN             NaN
                                                                                        BorderlineSMOTE    NaN
                                                                                        SMOTE              NaN
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN             NaN
                                                                                        BorderlineSMOTE    NaN
                                                                                        SMOTE              NaN
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN             NaN
                                                                                        BorderlineSMOTE    NaN
                                                                                        SMOTE              NaN
                                     criterion=entropy, max_depth=10, max_features=N... ADASYN             NaN

In [12]:
comparison_info_detailed_exploded = comparison_info_detailed.stack(
    level=[1, 2]
).reset_index()

max_options_detailed = comparison_info_detailed_exploded.loc[
    comparison_info_detailed_exploded.groupby(
        ["dataset_name", "oversampler_name", "n_neighbors", "param_name"]
    )["mean"].idxmax(),
    ["dataset_name", "oversampler_name", "n_neighbors", "oversampling_option"],
]
max_options_detailed = max_options_detailed.reset_index(drop=True)

max_options_detailed

,dataset_name,oversampler_name,n_neighbors,oversampling_option
0,Breast Cancer Wisconsin (Diagnostic),ADASYN,3,ADVANCED
1,Breast Cancer Wisconsin (Diagnostic),ADASYN,3,ADVANCED
2,Breast Cancer Wisconsin (Diagnostic),ADASYN,3,ADVANCED
3,Breast Cancer Wisconsin (Diagnostic),ADASYN,3,ADVANCED
4,Breast Cancer Wisconsin (Diagnostic),ADASYN,3,ADVANCED
...,...,...,...,...
49243,yeast_ml8,SMOTE,7,BASIC
49244,yeast_ml8,SMOTE,7,BASIC
49245,yeast_ml8,SMOTE,7,BASIC
49246,yeast_ml8,SMOTE,7,BASIC
49247,yeast_ml8,SMOTE,7,BASIC

In [13]:
aggregated_stats_df_detailed = pd.DataFrame(
    max_options_detailed.groupby(["oversampler_name", "n_neighbors"])[
        "oversampling_option"
    ].value_counts()
)
aggregated_stats_df_detailed

                                                  count
oversampler_name n_neighbors oversampling_option
ADASYN           3           ADVANCED              3847
                             BASIC                 1985
                 5           ADVANCED              3500
                             BASIC                 1684
                 7           ADVANCED              4373
                             BASIC                  811
BorderlineSMOTE  3           ADVANCED              3934
                             BASIC                 1898
                 5           ADVANCED              3498
                             BASIC                 1686
                 7           ADVANCED              3889
                             BASIC                 1295
SMOTE            3           ADVANCED              4126
                             BASIC                 1706
                 5           ADVANCED              4168
                             BASIC                 1664
                 7           ADVANCED              3486
                             BASIC                 1698

In [14]:
comparison_info_ultimate = agg_results_df_ultimate.pivot(
    columns=["n_neighbors", "oversampling_option"],
    index=["dataset_name", "oversampler_name"],
    values=["mean", "std"],
)
save_to_csv(comparison_info_ultimate, "comparison_info_ultimate.csv")
comparison_info_ultimate.sort_index().head(10)

                                                           mean            \
n_neighbors                                                   3
oversampling_option                                    ADVANCED     BASIC
dataset_name                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) ADASYN            0.946658       NaN
                                     BorderlineSMOTE   0.957486       NaN
                                     SMOTE             0.950486  0.937336
Ionosphere                           ADASYN            0.978396       NaN
                                     BorderlineSMOTE   0.972696       NaN
                                     SMOTE             0.974008       NaN
Pima Indians Diabetes                ADASYN            0.673334       NaN
                                     BorderlineSMOTE   0.660920       NaN
                                     SMOTE             0.640247       NaN
abalone                              ADASYN            0.420222  0.421155

                                                                           \
n_neighbors                                                   5
oversampling_option                                    ADVANCED     BASIC
dataset_name                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) ADASYN                 NaN       NaN
                                     BorderlineSMOTE        NaN       NaN
                                     SMOTE             0.951916       NaN
Ionosphere                           ADASYN                 NaN       NaN
                                     BorderlineSMOTE        NaN       NaN
                                     SMOTE             0.977882       NaN
Pima Indians Diabetes                ADASYN                 NaN       NaN
                                     BorderlineSMOTE        NaN       NaN
                                     SMOTE             0.644659       NaN
abalone                              ADASYN            0.418404  0.408118

                                                                       \
n_neighbors                                                   7
oversampling_option                                    ADVANCED BASIC
dataset_name                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) ADASYN                 NaN   NaN
                                     BorderlineSMOTE        NaN   NaN
                                     SMOTE                  NaN   NaN
Ionosphere                           ADASYN                 NaN   NaN
                                     BorderlineSMOTE        NaN   NaN
                                     SMOTE                  NaN   NaN
Pima Indians Diabetes                ADASYN                 NaN   NaN
                                     BorderlineSMOTE        NaN   NaN
                                     SMOTE                  NaN   NaN
abalone                              ADASYN            0.416444   NaN

                                                            std            \
n_neighbors                                                   3
oversampling_option                                    ADVANCED     BASIC
dataset_name                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) ADASYN            0.020996       NaN
                                     BorderlineSMOTE   0.015927       NaN
                                     SMOTE             0.027836  0.035455
Ionosphere                           ADASYN            0.012403       NaN
                                     BorderlineSMOTE   0.013647       NaN
                                     SMOTE             0.012514       NaN
Pima Indians Diabetes                ADASYN            0.026491       NaN
                                     BorderlineSMOTE   0.033860       NaN
                                     SMOTE             0.034729       NaN
abalone                              ADASYN            0.036410  0.036031

                                                                           \
n_neighbors                                                   5
oversampling_option                                    ADVANCED     BASIC
dataset_name                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) ADASYN                 NaN       NaN
                                     BorderlineSMOTE        NaN       NaN
                                     SMOTE             0.026760       NaN
Ionosphere                           ADASYN                 NaN       NaN
                                     BorderlineSMOTE        NaN       NaN
                                     SMOTE             0.009818       NaN
Pima Indians Diabetes                ADASYN                 NaN       NaN
                                     BorderlineSMOTE        NaN       NaN
                                     SMOTE             0.033887       NaN
abalone                              ADASYN            0.036912  0.030307


n_neighbors                                                   7
oversampling_option                                    ADVANCED BASIC
dataset_name                         oversampler_name
Breast Cancer Wisconsin (Diagnostic) ADASYN                 NaN   NaN
                                     BorderlineSMOTE        NaN   NaN
                                     SMOTE                  NaN   NaN
Ionosphere                           ADASYN                 NaN   NaN
                                     BorderlineSMOTE        NaN   NaN
                                     SMOTE                  NaN   NaN
Pima Indians Diabetes                ADASYN                 NaN   NaN
                                     BorderlineSMOTE        NaN   NaN
                                     SMOTE                  NaN   NaN
abalone                              ADASYN            0.036409   NaN

In [15]:
comparison_info_ultimate_exploded = comparison_info_ultimate.stack(
    level=[1, 2]
).reset_index()

max_options_ultimate = comparison_info_ultimate_exploded.loc[
    comparison_info_ultimate_exploded.groupby(
        ["dataset_name", "oversampler_name", "n_neighbors"]
    )["mean"].idxmax(),
    ["dataset_name", "oversampler_name", "n_neighbors", "oversampling_option"],
]
max_options_ultimate = max_options_ultimate.reset_index(drop=True)

max_options_ultimate

,dataset_name,oversampler_name,n_neighbors,oversampling_option
0,Breast Cancer Wisconsin (Diagnostic),ADASYN,3,ADVANCED
1,Breast Cancer Wisconsin (Diagnostic),BorderlineSMOTE,3,ADVANCED
2,Breast Cancer Wisconsin (Diagnostic),SMOTE,3,ADVANCED
3,Breast Cancer Wisconsin (Diagnostic),SMOTE,5,ADVANCED
4,Ionosphere,ADASYN,3,ADVANCED
...,...,...,...,...
223,yeast_ml8,BorderlineSMOTE,5,BASIC
224,yeast_ml8,BorderlineSMOTE,7,BASIC
225,yeast_ml8,SMOTE,3,BASIC
226,yeast_ml8,SMOTE,5,BASIC
227,yeast_ml8,SMOTE,7,BASIC

In [16]:
aggregated_stats_df_ultimate = pd.DataFrame(
    max_options_ultimate.groupby(["oversampler_name", "n_neighbors"])[
        "oversampling_option"
    ].value_counts()
)
aggregated_stats_df_ultimate

                                                  count
oversampler_name n_neighbors oversampling_option
ADASYN           3           ADVANCED                18
                             BASIC                    9
                 5           ADVANCED                17
                             BASIC                    7
                 7           ADVANCED                20
                             BASIC                    4
BorderlineSMOTE  3           ADVANCED                18
                             BASIC                    9
                 5           ADVANCED                17
                             BASIC                    7
                 7           ADVANCED                18
                             BASIC                    6
SMOTE            3           ADVANCED                20
                             BASIC                    7
                 5           ADVANCED                20
                             BASIC                    7
                 7           ADVANCED                18
                             BASIC                    6

# Charts

## Basic comparison top 3

In [17]:
for dataset in datasets:
    df = results_df[results_df["dataset_name"] == dataset]
    df_agg = agg_results_df[agg_results_df["dataset_name"] == dataset]

    best_params = (
        df_agg.sort_values("mean", ascending=False)["param_name"].head(3).to_numpy()
    )
    ratio = dataset_info[dataset_info["dataset"] == dataset]["ratio (0 : 1)"].values[0]

    figure, axs = plt.subplots(
        nrows=3, ncols=1, figsize=(20, 12), sharey=True, sharex=True
    )
    axs = axs.flatten()

    for i, (ax, param) in enumerate(zip(axs, best_params)):
        cur_df = df[df["param_name"] == param]
        create_results_bar_plot(ax=ax, df=cur_df, param=param, pallette=pallette, i=i)

    plt.suptitle(f"F1 Score Comparison for {dataset} (Ratio: {ratio})", fontsize=20)
    save_plot(
        os.path.join("basic_comparison_top_3", f"f1_score_comparison_{dataset}.png")
    )

In [18]:
aggregated_stats_df_detailed = aggregated_stats_df_detailed.reset_index()
aggregated_stats_df_detailed["oversampling_hue"] = (
    aggregated_stats_df_detailed["oversampler_name"]
    + "_"
    + aggregated_stats_df_detailed["n_neighbors"].astype(str)
)

fig, ax = plt.subplots(figsize=(12, 6))

create_results_bar_plot(
    ax=ax,
    df=aggregated_stats_df_detailed,
    param="oversampling_option",
    pallette=pallette,
    target="count",
    y_label="Count",
    bbox_right=1.22,
    round_digits=0,
)

save_plot(os.path.join("comparison", "detailed_scores.png"))

In [19]:
aggregated_stats_df_ultimate = aggregated_stats_df_ultimate.reset_index()
aggregated_stats_df_ultimate["oversampling_hue"] = (
    aggregated_stats_df_ultimate["oversampler_name"]
    + "_"
    + aggregated_stats_df_ultimate["n_neighbors"].astype(str)
)

fig, ax = plt.subplots(figsize=(12, 6))

create_results_bar_plot(
    ax=ax,
    df=aggregated_stats_df_ultimate,
    param="oversampling_option",
    pallette=pallette,
    target="count",
    y_label="Count",
    bbox_right=1.22,
    round_digits=0,
)

save_plot(os.path.join("comparison", "ultimate_scores.png"))